# Generated by Django 3.1.7 on 2021-02-28 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_centre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_alloted',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_alloted',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='tutorial_centre.teacher'),
        ),
    ]
